name: number_sliding_puzzle
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  audioplayers: ^0.13.2
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/tiles/wood/
    - assets/images/game_background_images/
    - assets/sounds/pop.mp3
